# -*- coding: utf-8 -*-
"""220411100158_Modul4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BCqhIrhBBJJiZH2mBJoD7cOeEV2tzIFm

# Nomor 1
"""

def bublesort(data):
  n = len(data)
  start, stop = 0, n-1
  print("data = {}\n".format(data))
  for i in range(n):
    if i % 2 == 0:
      for j in range(start, stop, 2):
        if data[j] > data[j + 1]:
          data[j], data[j + 1] = data[j + 1], data[j]
      print("data genap-ganjil sorting => {}".format(data))
    else:
      for j in range(start+1, stop, 2):
        if data[j] > data[j + 1]:
          data[j], data[j + 1] = data[j + 1], data[j]
      print("data ganjil-genap sorting => {}\n".format(data))
  return f"data urut = {data}"
data =  [13, 12, 10, 8, 7, 5, 11, 2]
print(bublesort(data))

"""# Nomor 2"""

def selectionSort(data):
  n = len(data)
  print("\nData awal = {}".format(data))
  for i in range(n//2):
    min = i
    max = i
    print(f"itererasi ke-{i+1}: ")
    for j in range(i+1, n-i):
      if data[j] < data[min]:
        min = j
      elif data[j] > data[max]:
        max = j
    data[i], data[min] = data[min], data[i]
    print(f"\turut data min : {data}")
    data[n-i-1], data[max] = data[max], data[n-i-1]
    print(f"\turut data max : {data}")
  return f"\ndata urut : {data}"
data = [10, 2, 5, 8, 1, 20, 7, 12, 4]
print(selectionSort(data))